language: haskell

env:
  - GHC=7.6.3
  - GHC=head

before_install:
  - sudo apt-get libgmp
  - make ghc-$GHC
  - cabal install cabal-install
  - cabal --version

install:
  - make init

script:
  - make install

after_script:
  - cat dist/test/th-desugar-*-spec.log 
