language: haskell

env:
  - GHC=7.6.3
  - GHC=7.8rc2
  - GHC=head

before_install:
  - sudo apt-get install libgmp3c2 libgmp3-dev libghc-zlib-dev -y
  - make ghc-$GHC
  - cabal install cabal-install
  - $HOME/.cabal/bin/cabal --version

install:
  - make init

script:
  - make install

after_script:
  - cat dist/test/th-desugar-*-spec.log 

# Taken from github.com/hvr/multi-ghc-travis
# NB: don't set `language: haskell` here

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.1 # see note about Alex/Happy
# - GHCVER=head  # see section about GHC HEAD snapshots

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

 - |
   if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.1" ]; then
     $CABAL install happy alex
     export PATH=$HOME/.cabal/bin:$PATH
   fi

install:
 - cabal-1.18 update
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal-1.18 configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal-1.18 build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal-1.18 test
 - cabal-1.18 check
 - cabal-1.18 sdist   # tests that a source-distribution can be generated

# The following scriptlet checks that the resulting source distribution can be built & installed
 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal-1.18 install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi